# GitHub 用户名 (必须改)
owner: Ghfftn
# 仓库名 (必须改，就是你第一步Fork时起的名字，比如 status)
repo: jk

# 自定义域名 (关键！)
cname: status.sshup.com

sites:
  - name: 我的主页
    url: https://sshup.com
    method: GET
    expectedStatusCodes: [200]
    
    
status-website:
  # 页面左上角的标题
  name: SSHUP 服务状态
  # 页面右上角的链接
  navbar:
    - title: 状态
      href: /
    - title: 首页
      href: https://sshup.com
  # 汉化与自定义提示
  introTitle: "**服务实时监控**"
  introMessage: "这里展示了 sshup.com 各项服务的实时运行状态。"
